version: '3'
services:
  wordle-app:
    container_name: wordle-app
    restart: always
    image: darwinbecker/wordle
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
