export const biology = {
  aerob: "Luftsauerstoff (zum Leben) benötigend, auf Sauerstoff aus der Luft angewiesen",
  Alula: "Federn am Daumen des Vogelflügels",
  Ambra: "fettige Ausscheidung aus dem Darm des Pottwals",
  Aorta: "größte Arterie, Hauptschlagader",
  atzen: "die Vogelbrut füttern",
  Augen: "Sehorgan des Menschen und vieler Tiere",
  aural: "das Ohr betreffend, Ohrmuschel",
  Bauch: "zwischen Zwerchfell und Becken liegender (vorgewölbter) Teil des Rumpfes",
  Blase: "häutiges Hohlorgan der Menschen, der Tiere, in dem sich Urin ansammelt, Harnblase",
  Braue: "Haarbogen über dem Auge",
  Brust: "Vorderteil des menschlichen, tierischen Körpers zwischen Hals und Magengrube; milchgebendes, paariges Organ des weiblichen Oberkörpers von halbkugeliger Form",
  Bulla: "verschiedene knöcherne, blasenartige Strukturen",
  Busen: "weibliche Brust",
  Denim: "robustes, typischerweise aus Baumwolle gefertigtes Gewebe in Köperbindung, das insbesondere für Jeans benutzt wird",
  Edukt: "Ausgangsgestein bei der Metamorphose",
  Eisen: "Eisen zählt zu den Spurenelementen. Es ist an vielen Prozessen im menschlichen Organismus beteiligt, u.a. am Sauerstofftransport als Bestandteil des roten Blutfarbstoffes (Hämoglobin) und an der Speicherung von Sauerstoff in der Muskulatur",
  Eiter: "bei bakterieller Entzündung im Körper entstehendes gelbgrünliches Gemisch aus abgestorbenen Gewebeteilen, weißen Blutkörperchen und Bazillen",
  Ekzem: "juckende, oft nässende Entzündung der Hautoberfläche",
  Enzym: "ein Stoff, der aus biologischen Riesenmolekülen besteht und als Katalysator eine chemische Reaktion beschleunigen kann; Ferment, Biokatalysator",
  euter: "in der Leistengegend von Einhufern und Wiederkäuern sitzende große Milchdrüse, die gemolken wird",
  Falte: "unregelmäßige, vertiefte Linie in der Haut, Hautfalte",
  Faust: "geballte Hand; Hand mit geballten Fingern",
  Ferse: "hinterster, gewölbter Teil des Fußes, Hacke",
  Figur: "äußere menschliche Gestalt, Erscheinung; (künstlerische) Menschendarstellung, Tierdarstellung",
  Flaum: "Gesamtheit der Flaumfedern oder feiner, weicher Haarwuchs, besonders der erste sprossende Bart",
  Fluke: "quer stehende Schwanzflosse des Wals",
  Gamet: "Geschlechtszelle, Keimzelle; der geschlechtlichen Fortpflanzung dienende Zelle",
  Genom: "Gen(e), Erbgut; Gesamtheit der Erbinformation eines vielzelligen Organismus, einer Zelle oder eines Virus",
  

}