export const botany = { 
  Abies: "Wissenschaftlicher Name für: Tanne,Tannenbaum",
  Afrik: "Palmfaser",
  Ahorn: "Laubbaum mit handförmigen, gelappten Blättern und geflügelter, zweiteiliger Frucht",
  Allee: "von (hohen) Bäumen eingefasste Straße",
  Alsem: "Pflanzenart; Bitterer Beifuß, Echt-Wermut, Echter Wermut",
  Anbau: "das Anpflanzen",
  bienn: "zweijährig (von Pflanzen mit zweijähriger Lebensdauer, die erst im zweiten Jahr blühen und Frucht tragen)",
  Binse: "grasartige Pflanze, die an feuchten, moorigen Stellen wächst und deren stängelähnliche Blätter zu Geflechten verwendet werden",
  Birke: "Laubbaum mit weißer, abblätternder Rinde und hellgrünen, doppelt gesägten Blättern, der hochwertiges Nutzholz liefert und dessen Zweige als Symbol des Frühlings ein beliebter Schmuck sind",
  Blatt: "flächiges, meist durch Chlorophyll grün gefärbtes Organ der höheren Pflanzen, das zur Assimilation, Wasserverdunstung und Atmung dient",
  Blume: "niedrig gewachsene, krautige Pflanze, die Blüten hervorbringt",
  Blust: "Blütezeit, das Blühen",
  Bolle: "große Zwiebel",
  Borke: "Baumrinde bzw. periphere Gewebeschicht eines Baumes",
  Buche: "Laubbaum mit hohem, schlankem Stamm und silbergrauer, glatter Rinde, der kerniges Holz und ölhaltige Früchte besitzt",
  Buchs: "Buchsbaum, immergrüner Zierstrauch mit kleinen, fast runden Blättern, der meist zur Einfassung von Beeten dient",
  Buhne: "quer ins Wasser hineingebauter Damm, der als Uferschutz dient",
  Busch: "dicht belaubter oder mit Blüten bedeckter Strauch, Strauß",
  Chili: "scharfe Paprika, Peperoni; sorte der Beerenfrucht von Pflanzen der Gattung Capsicum",
  Copal: "Baumharz; Sammelbezeichnung für Baumharze verschiedener botanischer Herkunft, die als Räucherwerk und für hochwertige Farben und Lacke verwendet werden",
  Cumin: "Kreuzkümmel, Kumin; Pflanze aus der Familie der Doldenblütler, deren getrocknete Früchte als Gewürz genutzt werden",
  Dille: "doldenblütiges Gewürzkraut, das zum Einlegen von Gurken und zum Anrichten von Salaten Verwendung findet",
  duerr: "dürr, sehr trocken, verdorrt oder sehr mager",
  Durum: "Hartweizen, auch Durum, Durumweizen oder Glasweizen genannt, ist nach Weichweizen die wirtschaftlich bedeutendste Weizen-Art",
  Eiche: "hoher und breiter Laubbaum mit buchtig gelappten Blättern und hartem, schwerem, dauerhaftem Holz, dessen Frucht in einem Becher sitzt und der infolge seines kraftvollen Wuchses und seines oft erreichten hohen Alters als Sinnbild der Stärke und Kraft gilt",
  Erbse: "artenreiche Gemüsepflanze aus der Familie der Schmetterlingsblütler mit paarigen, in Ranken auslaufenden Blättern, deren kugelförmige, in Schoten sitzende Samen als Nahrungsmittel verwendet werden",
  Erika: "Heidekraut, rotlilablühender Zwergstrauch mit immergrünen Blättern, der auf sandigem, kalkarmem, saurem Boden wächst, Erika",
  Ernte: "die reifen Früchte der Felder und Gärten, die eingesammelt und eingebracht werden, das Ernten",
  Esche: "Laubbaum mit gefiederten Blättern und geflügelten Früchten, der wertvolles Holz für Möbel, Werkzeugstiele und Sportgeräte liefert",
  Esope: "zur Gattung der Pappeln gehörender Laubbaum, dessen Blätter durch die hochkantige Stellung des Blattstiels beim leisesten Luftzug ins Zittern geraten, Zitterpappel",
  Flora: "die Pflanzenwelt innerhalb bestimmter Naturverhältnisse",
  Forke: "große Gabel mit drei oder vier Zinken an einem langen Stiel für die Arbeit im Garten, im Stall o.Ä.",
  Forle: "Die Kiefern, Föhren, Sjüren, Forlen oder Dählen bilden eine Pflanzengattung in der Familie der Kieferngewächse innerhalb der Nadelholzgewächse",
  Forst: "bewirtschaftete Waldfläche",
  Gagel: "Gagelstrauch, auch Gagel oder Moor-Gagel und Talgstrauch, -busch sowie Talgbaum genannt, ist eine Pflanzenart in der Familie der Gagelstrauchgewächse. Er ist in Nordamerika und im nordwestlichen Europa weitverbreitet und ist in Europa die einzige Art der Familie Myricaceae",
  Garbe: "Eine Garbe ist in der Landwirtschaft ein Bündel aus Getreidehalmen, einschließlich der sich am oberen Ende befindenden Ähren. Mehrere Garben werden auf dem Feld zu Diemen zum Trocknen zusammengestellt",
  Gemma: "Knospe; In der Botanik ist Knospe (auch Auge, lateinisch oculus oder Gemma genannt) der jugendliche Zustand eines Sprosses, in welchem die Stängelglieder desselben noch ganz kurz, die an denselben befindlichen Blätter daher noch dicht zusammengedrängt und in ihrer Entwicklung ebenfalls noch wenig fortgeschritten sind",
  


}
