export const chemistry = {
  Abgas: "bei Verbrennungsvorgängen abströmendes Gas",
  Albit: "meist weißes, wichtiges gesteinsbildendes Mineral",
  Algin: "aus Braunalgen gewonnenes chemisches Produkt von vielfacher technischer Verwendbarkeit",
  Alkan: "gesättigter azyklischer Kohlenwasserstoff",
  Alken: "Alkene, chemische Verbindungen aus Gruppe der Kohlenwasserstoffen",
  Alkin: "ungesättigter Kohlenwasserstoff",
  Argon: "sehr träge reagierendes, farb- und geruchloses Edelgas",
  Beize: "Ätzflüssigkeit, Ätzmittel",
  Bixin: "ein in der Natur vorkommender gelb-oranger Farbstoff aus der Gruppe der Carotinoide, welches aus Annatto gewonnen wird und als Lebensmittel- und Kosmetikfarbstoff eingesetzt wird",
  Borax: "in der Natur selten vorkommendes, meist weißes, graues oder farbloses kristallisierendes Mineral; Natriumsalz der Borsäure, Natriumtetraborat",
  Botox: "Nervengift, das in stark verdünnter Form zum Glätten von Falten gespritzt wird; Botulin, Botulinum-Neurotoxin, Botulinumtoxin, Botulinustoxin",
  Celit: "eine weißliche, pulverförmige Substanz, die hauptsächlich aus den Schalen fossiler Kieselalgen besteht",
  Chlor: "gelbgrünes Gas von durchdringendem Geruch, das sich (unter starker Wärmeentwicklung) mit fast allen anderen chemischen Elementen verbindet, in der Natur aber nur in chemischen Verbindungen vorkommt",
  Chrom: "silberweiß glänzendes, zähes Schwermetall, das bei normalen Temperaturen in Luft und Wasser nicht oxydiert",
  Codon: "drei aufeinander folgende Basen einer Nukleinsäure, die den Schlüssel für eine Aminosäure im Protein darstellen; Triplett, Basentriplett",
  Crack: "zum Rauchen bestimmte Droge aus Kokainsalz und Natron",
  Dunst: "durch Wasserdampf oder Verunreinigungen getrübte Atmosphäre; stark riechende, warme Luft, die oft als lästig und erstickend empfunden wird",
  Edukt: "aus Rohstoffen abgeschiedener Stoff",
  Eisen: "häufigstes und sehr wichtiges, in feuchter Luft rostendes, magnetisches Schwermetall von silberweißer Farbe, das hart und elastisch ist und zu Stahl weiterverarbeitet wird",
  eisig: "kalt wie Eis, sehr kalt oder völlig gefühllos und voll Ablehnung",
  Enzym: "ein Stoff, der aus biologischen Riesenmolekülen besteht und als Katalysator eine chemische Reaktion beschleunigen kann; Ferment, Biokatalysator",
  Ethin: "ein farbloses Gas mit der Summenformel C₂H₂. Es ist der einfachste Vertreter aus der homologen Reihe der Alkine. Ethin ist von großer industrieller Bedeutung. Es dient als Ausgangsverbindung bei der großtechnischen Herstellung wichtiger Grundchemikalien",
  Feuer: "die Entwicklung von Licht und Wärme in Form von Flammen beim Verbrennungsvorgang",
  Floez: "meist annähernd horizontal gelagerte Schicht technisch nutzbarer Gesteine oder Minerale von großer Flächenausdehnung, besonders Kohle, Erze, Salze",
  Fluid: "Flüssigkeit, flüssiges Mittel; zusammenfassende Bezeichnung für Flüssigkeiten, Gase und Plasmen",
  Fluor: "gasförmiges Element von grünlichgelber Farbe und stechendem Geruch",
}
