export const food = {
  Aioli: "kalte Creme (Vorspeise, Knoblauchmayonnaise",
  Apero: "schweizerisch: Aperitif, alkoholisches Getränk",
  Apfel: "Frucht des Apfelbaums",
  Aroma: "(angenehm) würziger Geruch, Geschmack; Würzmittel, Essenz",
  Aspik: "durch Auskochen von Fleisch‍(knochen) oder Fisch gewonnene oder mit Gelatine hergestellte säuerliche Gallerte für die Zubereitung bestimmter Speisen (besonders Sülze)",
  Bagel: "ursprünglich aus der jüdischen Küche stammendes, ringförmiges, brötchenartiges Gebäckstück aus Hefeteig, das zunächst kurz in Wasser gekocht und anschließend gebacken wird",
  Beere: "kleine, fleischige und saftige Frucht, deren Gewebe von einer dünnen Haut umschlossen ist und die Samenkerne enthält",
  Bemme: "(sächsisch) gestrichene, belegte Scheibe Brot",
  Birne: "Frucht des Birnbaums",
  Bohne: "artenreiche Gemüsepflanze aus der Familie der Schmetterlingsblütler, die, buschig oder an Stangen sich emporwindend, in unseren Gärten viel angebaut wird, da ihre lang herabhängenden Früchte und ihre nierenförmigen Samen gern gegessen werden",
  Bolle: "große Zwiebel",
  Braet: "Brätmasse, Fleischbrät, sehr feine Masse aus zerkleinertem Fleisch, die besonders zur Herstellung von Wurst, Fleischkäse o. Ä. verwendet wird",
  Chili: "scharfe Paprika, Peperoni; sorte der Beerenfrucht von Pflanzen der Gattung Capsicum",
  Chips: "Essen: sehr dünne, frittierte Scheibe von Gemüse, insbesondere Kartoffeln, oder aus speziellem Teig, die kalt und meist in größerer Anzahl verzehrt wird",
  Cider: "französischer Apfelwein aus der Normandie oder Bretagne",
  Cover: "Titelseite einer Illustrierten; Deckblatt, Titel, Titelbild",
  Creme: "feine, schaumige Süßspeise",
  Curry: "Mischung scharfer indischer Gewürze, meist mit dem Hauptbestandteil Kurkuma, die dem Gewürzpulver die gelbe Farbe gibt; scharfe Würzpaste aus verschiedenen Kräutern und Gewürzen; aus der indischen Küche stammendes Gericht aus Fleisch, Fisch oder Gemüse, das mit Curry gewürzt und meist mit Reis serviert wird",
  Diaet: "richtige Ernährungsweise, besondere Ernährungsweise, oft von Kranken; Schonkost, Krankenkost",
  Dille: "doldenblütiges Gewürzkraut, das zum Einlegen von Gurken und zum Anrichten von Salaten Verwendung findet",
  Donut: "handtellergroßer amerikanischer/kanadischer Krapfen aus Hefeteig oder Rührteig",
  Drink: "alkoholisches Mischgetränk",
  Drohn: "Drohne, fachsprachlich auch der Drohn, ist das männliche Tier bei Wildbienen, Honigbienen und Wespen. Diese staatenbildenden Arten aus der Ordnung der Hautflügler besitzen drei unterschiedliche Morphen: Königin, Arbeiterin und Drohne",
  Durst: "starkes Bedürfnis zu trinken",
  Durum: "Hartweizen, auch Durum, Durumweizen oder Glasweizen genannt, ist nach Weichweizen die wirtschaftlich bedeutendste Weizen-Art",
  Eisen: "Eisen zählt zu den Spurenelementen. Es ist an vielen Prozessen im menschlichen Organismus beteiligt, u.a. am Sauerstofftransport als Bestandteil des roten Blutfarbstoffes (Hämoglobin) und an der Speicherung von Sauerstoff in der Muskulatur",
  Erbse: "artenreiche Gemüsepflanze aus der Familie der Schmetterlingsblütler mit paarigen, in Ranken auslaufenden Blättern, deren kugelförmige, in Schoten sitzende Samen als Nahrungsmittel verwendet werden",
  Ernte: "die reifen Früchte der Felder und Gärten, die eingesammelt und eingebracht werden, das Ernten",
  essen: "etwas (meist feste Nahrung) zu sich nehmen, speisen, verkosten",
  Essig: "flüssiges, saures Würzmittel und Frischhaltemittel",
  Farin: "feiner, nicht raffinierter, gelblich brauner, leicht feuchter Zucker oder Puderzucker",
  Filet: "zartes Lendenstück vom Schwein oder Rind, das zum Braten geeignet ist; Fischstück ohne Gräten und Haut; Bruststück vom Geflügel",
  Fisch: "schuppiges, wechselwarmes Wirbeltier (mit seitlich abgeflachtem Körper), das im Wasser lebt und dazu mit Schwimmblase, Kiemen und Flossen ausgestattet ist",
  garen: "garen, dämpfen, dünsten, kochen, schmoren",
  Gelee: "durchsichtige, gallertartige Masse: (unter Zusatz von Zucker) eingedickter Fruchtsaft oder durch Gelatine gesteifte Süßspeise",


}
